table 'Country Priority'
	lineageTag: e88ba3f0-93a2-4810-98f2-b1f41edce7d8

	column company_country
		dataType: string
		isKey
		lineageTag: 5ec4699c-2a31-4cd6-ad19-8774fcac2af8
		summarizeBy: none
		sourceColumn: company_country

	column lead_count
		dataType: int64
		formatString: 0
		lineageTag: 2cf0ec0a-2a46-4f2b-9471-21e385eae5e0
		summarizeBy: sum
		sourceColumn: lead_count

	column company_count
		dataType: int64
		formatString: 0
		lineageTag: d6a9858d-7d0c-4f2d-bb4f-f4d5b78beec2
		summarizeBy: sum
		sourceColumn: company_count

	column executive_share
		dataType: double
		formatString: 0.0 %
		lineageTag: f5a2b1f2-6714-4354-ae6b-31a4e5a5c88e
		summarizeBy: none
		sourceColumn: executive_share

	column compliance_share
		dataType: double
		formatString: 0.0 %
		lineageTag: 25b46d05-85ef-4f6d-8f2e-f738652a22f8
		summarizeBy: none
		sourceColumn: compliance_share

	column mismatch_share
		dataType: double
		formatString: 0.0 %
		lineageTag: c3bb4b78-d630-4e27-b696-d6746b8f6a1a
		summarizeBy: none
		sourceColumn: mismatch_share

	column country_rank
		dataType: int64
		formatString: 0
		lineageTag: 6fe1415f-5f35-4126-a82c-7b45bb7d92c6
		summarizeBy: none
		sourceColumn: country_rank

	column priority_tier
		dataType: string
		lineageTag: 4fcb72f8-eec9-42c0-8bae-c9d9017b7171
		summarizeBy: none
		sourceColumn: priority_tier

	column messaging_angle
		dataType: string
		lineageTag: ee88ba37-d903-4d4c-85be-fb289db1e770
		summarizeBy: none
		sourceColumn: messaging_angle

	column strategic_recommendation
		dataType: string
		lineageTag: 7693f432-2f01-46cb-b41d-614bd81890b1
		summarizeBy: none
		sourceColumn: strategic_recommendation

	partition 'Country Priority' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRoot & "\\dim_country_priority.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{
				        {"company_country", type text},
				        {"lead_count", Int64.Type},
				        {"company_count", Int64.Type},
				        {"executive_share", type number},
				        {"compliance_share", type number},
				        {"mismatch_share", type number},
				        {"country_rank", Int64.Type},
				        {"priority_tier", type text},
				        {"messaging_angle", type text},
				        {"strategic_recommendation", type text}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
